#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.147                       #
#------------------------------------------------------------------------------#


WORKDIR = `pwd`

CC = gcc
CXX = g++
AR = ar
LD = g++
WINDRES = windres

INC = -I/usr/include/hiredis
CFLAGS = -Wall -std=c11 -D_GNU_SOURCE
RESINC = 
LIBDIR = 
LIB = -levent -lhiredis
LDFLAGS = 

INC_DEBUG = $(INC)
CFLAGS_DEBUG = $(CFLAGS) -g
RESINC_DEBUG = $(RESINC)
RCFLAGS_DEBUG = $(RCFLAGS)
LIBDIR_DEBUG = $(LIBDIR)
LIB_DEBUG = $(LIB)
LDFLAGS_DEBUG = $(LDFLAGS)
OBJDIR_DEBUG = obj/Debug
DEP_DEBUG = 
OUT_DEBUG = bin/Debug/bugart

INC_RELEASE = $(INC)
CFLAGS_RELEASE = $(CFLAGS) -O2
RESINC_RELEASE = $(RESINC)
RCFLAGS_RELEASE = $(RCFLAGS)
LIBDIR_RELEASE = $(LIBDIR)
LIB_RELEASE = $(LIB)
LDFLAGS_RELEASE = $(LDFLAGS) -s
OBJDIR_RELEASE = obj/Release
DEP_RELEASE = 
OUT_RELEASE = bin/Release/bugart

OBJ_DEBUG = $(OBJDIR_DEBUG)/bugart.o $(OBJDIR_DEBUG)/example.o $(OBJDIR_DEBUG)/trie.o

OBJ_RELEASE = $(OBJDIR_RELEASE)/bugart.o $(OBJDIR_RELEASE)/example.o $(OBJDIR_RELEASE)/trie.o

all: debug release

clean: clean_debug clean_release

before_debug: 
	test -d bin/Debug || mkdir -p bin/Debug
	test -d $(OBJDIR_DEBUG) || mkdir -p $(OBJDIR_DEBUG)

after_debug: 

debug: before_debug out_debug after_debug

out_debug: before_debug $(OBJ_DEBUG) $(DEP_DEBUG)
	$(LD) $(LIBDIR_DEBUG) -o $(OUT_DEBUG) $(OBJ_DEBUG)  $(LDFLAGS_DEBUG) $(LIB_DEBUG)

$(OBJDIR_DEBUG)/bugart.o: bugart.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c bugart.c -o $(OBJDIR_DEBUG)/bugart.o

$(OBJDIR_DEBUG)/example.o: example.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c example.c -o $(OBJDIR_DEBUG)/example.o

$(OBJDIR_DEBUG)/trie.o: trie.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c trie.c -o $(OBJDIR_DEBUG)/trie.o

clean_debug: 
	rm -f $(OBJ_DEBUG) $(OUT_DEBUG)
	rm -rf bin/Debug
	rm -rf $(OBJDIR_DEBUG)

before_release: 
	test -d bin/Release || mkdir -p bin/Release
	test -d $(OBJDIR_RELEASE) || mkdir -p $(OBJDIR_RELEASE)

after_release: 

release: before_release out_release after_release

out_release: before_release $(OBJ_RELEASE) $(DEP_RELEASE)
	$(LD) $(LIBDIR_RELEASE) -o $(OUT_RELEASE) $(OBJ_RELEASE)  $(LDFLAGS_RELEASE) $(LIB_RELEASE)

$(OBJDIR_RELEASE)/bugart.o: bugart.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c bugart.c -o $(OBJDIR_RELEASE)/bugart.o

$(OBJDIR_RELEASE)/example.o: example.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c example.c -o $(OBJDIR_RELEASE)/example.o

$(OBJDIR_RELEASE)/trie.o: trie.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c trie.c -o $(OBJDIR_RELEASE)/trie.o

clean_release: 
	rm -f $(OBJ_RELEASE) $(OUT_RELEASE)
	rm -rf bin/Release
	rm -rf $(OBJDIR_RELEASE)

.PHONY: before_debug after_debug clean_debug before_release after_release clean_release

